### ISSUE TITLE
自定义导航bug

### ISSUE THREAD

**Issue by baxsad** [litt1e-p/LPScrollFullScreen#1]
只对默认的导航有效果，设置了setBarTintColor就会出问题（颜色会滞留顶部）

**Comment by litt1e-p** [comment]
@iURWang  thanks for the issue, setting for UINavigationBar's barTintColor is beyond the scope of LPScrollFullScreen. but what I will suggest is that you can control the barTintColor via viewWillAppear & viewWillDisappear methods. eg.

``` swift
// in viewWillAppear
self.navigationController.navigationBar.barTintColor = `your color`;
// in viewWillDisappear
self.navigationController.navigationBar.barTintColor = nil; //the default value
```
